English|(Nominative)<br />Vardinikas|(Ablative)<br />įnagininkas
---|---|---
first|pirmas|primu
second|antras|antru
third|trečias|trečiu
fourth|ketvirtas|ketvirtu
fifth|penktas|penktu
sixth|šeštas|šeštu
seventh|septintas|septintu
eigtieth|aštuntas|aštuntu
ninth|devintas|devintu
tenth|dešimtas|dešimtu
eleventh|vienuoliktas|vienuoliktu
twelfh|dvyliktas|dvyliktu
thirteen|tryliktas|tryliktu
fourteen|keturioliktas|keturioliktu
fifteen|penkioliktas|penkioliktu
sixteen|šešioliktas|šešioliktu
seventeen|septynioliktas|septynioliktu
eighteen|aštuonioliktas|aštuonioliktu
nineteen|devynioliktas|devynioliktu
twentieth|dvidešimtas|dvidešimtu